# Generated by Django 5.1b1 on 2024-07-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films_post',
            new_name='Film',
        ),
    ]
